openapi: 3.0.1
info:
  title: What's Your Plan! Image Server API Docs
  description: What's Your Plan! Image Server API Description
  version: 1.0.0
servers:
- url: http://127.0.0.1:8080
tags: []
paths: {}
components:
  schemas: {}
